name: CI on Push

# Dispara somente em commits para a branch main
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Clonar o repositório e trocar para a branch main
      - name: Checkout código
        uses: actions/checkout@v4
        with:
          ref: main

      # 2. Instalar interpretador Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 3. Instalar dependências do projeto
      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Executar a aplicação (smoke test)
      - name: Executar API
        run: |
          nohup python app.py &
          sleep 5
          curl --fail http://localhost:5000/api/albuns
