name: CI on Pull Request

# Dispara em abertura, atualização ou reabertura de PR contra main
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Clonar o repositório e trocar para a branch de origem do PR
      - name: Checkout código do PR
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      # 2. Instalar Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 3. Instalar dependências
      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt


      # 4. Executar API (smoke test)
      - name: Executar API
        run: |
          nohup python app.py &
          sleep 5
          curl --fail http://localhost:5000/api/albuns
